/**
 * Ganon's Curse - dev-only browser for vanilla cutscenes.
 *
 * `gc_play_vanilla_cs <symbol>` plays any vanilla cutscene that SoH exports as
 * a named OTR asset; `gc_list_vanilla_cs [filter]` lists them. This exists to
 * answer one question cheaply - "what does that shot actually look like?" -
 * while scoping 4c/4d, which are built on reusing vanilla camera work.
 *
 * The 73 entries below are every cutscene with a name. They are generated by
 * scanning soh/assets/scenes for the ALIGN_ASSET declarations, so the table is
 * exactly what the game ships, not a hand-maintained guess. Cutscenes without a
 * name - notably everything in the Chamber of Sages (kenjyanoma) and the ending
 * scene (hiral_demo) - are NOT reachable this way; they are scene cutscene
 * layers, selected by entering the scene with cutsceneIndex >= 0xFFF0. See
 * docs/opening-cutscene.md in the ganons-curse repo.
 *
 * IMPORTANT CAVEAT: a cutscene's actor cues address actors by index in the
 * CURRENT scene. Playing a cutscene outside its home scene therefore gives you
 * its camera work and text, but any character it was meant to show will be
 * missing or wrong. To evaluate a character shot (e.g. the six *TrialSageCs
 * entries, all of which live in Ganon's Castle) you have to be standing in the
 * scene that owns it. Camera-only shots travel fine - that is exactly what the
 * 4b pipeline relies on.
 *
 * Dev tool: no gating beyond the debug console itself, and nothing here is
 * reachable in normal play.
 */
// Order matters - see the note in GanonsCurseCutscenes.cpp. Plain-C++ includes
// first, before the extern "C" block pulls in the functions.h chain.
#include <soh/OTRGlobals.h>
#include "soh/ShipInit.hpp"

#include <ship/Context.h>
#include <ship/debug/Console.h>

#include <algorithm>
#include <string>
#include <vector>

// Pulls in the functions.h/variables.h/macros.h chain in the order that defines
// PlayState, Vec3f/Vec3s and gSaveContext before anything below needs them.
#include "GanonsCurseCutscenes.h"

extern "C" {
extern PlayState* gPlayState;
}

#include <scenes/dungeons/bdan/bdan_scene.h>
#include <scenes/dungeons/ddan/ddan_scene.h>
#include <scenes/dungeons/ganon_tou/ganon_tou_scene.h>
#include <scenes/dungeons/ganontika/ganontika_scene.h>
#include <scenes/dungeons/ice_doukutu/ice_doukutu_scene.h>
#include <scenes/dungeons/jyasinboss/jyasinboss_scene.h>
#include <scenes/dungeons/ydan/ydan_scene.h>
#include <scenes/indoors/daiyousei_izumi/daiyousei_izumi_scene.h>
#include <scenes/indoors/hakasitarelay/hakasitarelay_scene.h>
#include <scenes/indoors/nakaniwa/nakaniwa_scene.h>
#include <scenes/indoors/tokinoma/tokinoma_scene.h>
#include <scenes/indoors/yousei_izumi_yoko/yousei_izumi_yoko_scene.h>
#include <scenes/misc/hakaana_ouke/hakaana_ouke_scene.h>
#include <scenes/overworld/spot00/spot00_scene.h>
#include <scenes/overworld/spot01/spot01_scene.h>
#include <scenes/overworld/spot02/spot02_scene.h>
#include <scenes/overworld/spot04/spot04_scene.h>
#include <scenes/overworld/spot05/spot05_scene.h>
#include <scenes/overworld/spot06/spot06_scene.h>
#include <scenes/overworld/spot07/spot07_scene.h>
#include <scenes/overworld/spot08/spot08_scene.h>
#include <scenes/overworld/spot09/spot09_scene.h>
#include <scenes/overworld/spot11/spot11_scene.h>
#include <scenes/overworld/spot12/spot12_scene.h>
#include <scenes/overworld/spot15/spot15_scene.h>
#include <scenes/overworld/spot16/spot16_scene.h>
#include <scenes/overworld/spot17/spot17_scene.h>
#include <scenes/overworld/spot18/spot18_scene.h>
#include <scenes/overworld/spot20/spot20_scene.h>

namespace {

struct VanillaCutscene {
    const char* name;
    const char* segment;
};

// Generated by scanning soh/assets/scenes for ALIGN_ASSET cutscene symbols.
const VanillaCutscene kVanillaCutscenes[] = {
    { "gDMTIntroCs", gDMTIntroCs },
    { "gDMTOwlCs", gDMTOwlCs },
    { "gDcOpeningCs", gDcOpeningCs },
    { "gDeathMountainCraterBoleroCs", gDeathMountainCraterBoleroCs },
    { "gDeathMountainCraterIntroCs", gDeathMountainCraterIntroCs },
    { "gDekuTreeIntroCs", gDekuTreeIntroCs },
    { "gDesertColossusIntroCs", gDesertColossusIntroCs },
    { "gFireBarrierCs", gFireBarrierCs },
    { "gFireTrialSageCs", gFireTrialSageCs },
    { "gForestBarrierCs", gForestBarrierCs },
    { "gForestTrialSageCs", gForestTrialSageCs },
    { "gGanonsCastleIntroCs", gGanonsCastleIntroCs },
    { "gGerudoFortressFirstCaptureCs", gGerudoFortressFirstCaptureCs },
    { "gGerudoFortressIntroCs", gGerudoFortressIntroCs },
    { "gGerudoValleyBridgeJumpFieldFortressCs", gGerudoValleyBridgeJumpFieldFortressCs },
    { "gGerudoValleyBridgeJumpFortressToFieldCs", gGerudoValleyBridgeJumpFortressToFieldCs },
    { "gGerudoValleyIntroCs", gGerudoValleyIntroCs },
    { "gGoronCityDarunia01Cs", gGoronCityDarunia01Cs },
    { "gGoronCityDaruniaCorrectCs", gGoronCityDaruniaCorrectCs },
    { "gGoronCityDaruniaWrongCs", gGoronCityDaruniaWrongCs },
    { "gGoronCityIntroCs", gGoronCityIntroCs },
    { "gGraveyardIntroCs", gGraveyardIntroCs },
    { "gGreatFairyDinsFireCs", gGreatFairyDinsFireCs },
    { "gGreatFairyDoubleDefenseCs", gGreatFairyDoubleDefenseCs },
    { "gGreatFairyDoubleMagicCs", gGreatFairyDoubleMagicCs },
    { "gGreatFairyFaroresWindCs", gGreatFairyFaroresWindCs },
    { "gGreatFairyMagicCs", gGreatFairyMagicCs },
    { "gGreatFairyNayrusLoveCs", gGreatFairyNayrusLoveCs },
    { "gHyruleCastleIntroCs", gHyruleCastleIntroCs },
    { "gHyruleFieldEastEponaJumpCs", gHyruleFieldEastEponaJumpCs },
    { "gHyruleFieldGateEponaJumpCs", gHyruleFieldGateEponaJumpCs },
    { "gHyruleFieldGetOoTCs", gHyruleFieldGetOoTCs },
    { "gHyruleFieldIntroCs", gHyruleFieldIntroCs },
    { "gHyruleFieldSouthEponaJumpCs", gHyruleFieldSouthEponaJumpCs },
    { "gHyruleFieldWestEponaJumpCs", gHyruleFieldWestEponaJumpCs },
    { "gHyruleFieldZeldaSongOfTimeCs", gHyruleFieldZeldaSongOfTimeCs },
    { "gIceCavernSerenadeCs", gIceCavernSerenadeCs },
    { "gJabuJabuIntroCs", gJabuJabuIntroCs },
    { "gKakarikoVillageIntroCs", gKakarikoVillageIntroCs },
    { "gKokiriForestDekuSproutCs", gKokiriForestDekuSproutCs },
    { "gLakeHyliaFireArrowsCS", gLakeHyliaFireArrowsCS },
    { "gLakeHyliaIntroCs", gLakeHyliaIntroCs },
    { "gLakeHyliaOwlCs", gLakeHyliaOwlCs },
    { "gLightBarrierCs", gLightBarrierCs },
    { "gLightTrialSageCs", gLightTrialSageCs },
    { "gLonLonRanchIntroCs", gLonLonRanchIntroCs },
    { "gMinuetCs", gMinuetCs },
    { "gRainbowBridgeCs", gRainbowBridgeCs },
    { "gShadowBarrierCs", gShadowBarrierCs },
    { "gShadowTrialSageCs", gShadowTrialSageCs },
    { "gSongOfStormsCs", gSongOfStormsCs },
    { "gSpiritBarrierCs", gSpiritBarrierCs },
    { "gSpiritBossNabooruKnuckleDefeatCs", gSpiritBossNabooruKnuckleDefeatCs },
    { "gSpiritBossNabooruKnuckleIntroCs", gSpiritBossNabooruKnuckleIntroCs },
    { "gSpiritTrialSageCs", gSpiritTrialSageCs },
    { "gSpot04Cs_10E20", gSpot04Cs_10E20 },
    { "gSunSongGraveSunSongTeachCs", gSunSongGraveSunSongTeachCs },
    { "gSunSongGraveSunSongTeachPart2Cs", gSunSongGraveSunSongTeachPart2Cs },
    { "gTempleOfTimeFirstAdultCs", gTempleOfTimeFirstAdultCs },
    { "gTempleOfTimeIntroCs", gTempleOfTimeIntroCs },
    { "gTempleOfTimePreludeCs", gTempleOfTimePreludeCs },
    { "gTowerBarrierCs", gTowerBarrierCs },
    { "gWaterBarrierCs", gWaterBarrierCs },
    { "gWaterTrialSageCs", gWaterTrialSageCs },
    { "gZeldasCourtyardGanonCs", gZeldasCourtyardGanonCs },
    { "gZeldasCourtyardLullabyCs", gZeldasCourtyardLullabyCs },
    { "gZeldasCourtyardMeetCs", gZeldasCourtyardMeetCs },
    { "gZeldasCourtyardWindowCs", gZeldasCourtyardWindowCs },
    { "gZorasDomainIntroCs", gZorasDomainIntroCs },
    { "gZorasFountainIntroCs", gZorasFountainIntroCs },
    { "spot02_scene_Cs_003C80", spot02_scene_Cs_003C80 },
    { "spot02_scene_Cs_005020", spot02_scene_Cs_005020 },
    { "spot05_scene_Cs_005730", spot05_scene_Cs_005730 },
};

int32_t PlayVanillaCutsceneCommand(std::shared_ptr<Ship::Console> console, std::vector<std::string> args,
                                   std::string* output) {
    if (gPlayState == nullptr) {
        if (output != nullptr) {
            *output = "no active play session";
        }
        return 1;
    }
    if (args.size() < 2) {
        if (output != nullptr) {
            *output = "usage: gc_play_vanilla_cs <symbol>  (see gc_list_vanilla_cs)";
        }
        return 1;
    }
    for (const VanillaCutscene& cs : kVanillaCutscenes) {
        if (args[1] == cs.name) {
            Cutscene_SetSegment(gPlayState, const_cast<char*>(cs.segment));
            gSaveContext.cutsceneTrigger = 1;
            if (output != nullptr) {
                *output = "playing " + args[1] +
                          " (actor shots only render correctly in the scene that owns them)";
            }
            return 0;
        }
    }
    if (output != nullptr) {
        *output = "unknown cutscene: " + args[1] + " - try gc_list_vanilla_cs";
    }
    return 1;
}

int32_t ListVanillaCutscenesCommand(std::shared_ptr<Ship::Console> console, std::vector<std::string> args,
                                    std::string* output) {
    std::string filter = args.size() >= 2 ? args[1] : "";
    std::string lowered = filter;
    std::transform(lowered.begin(), lowered.end(), lowered.begin(), ::tolower);

    std::string result;
    int32_t count = 0;
    for (const VanillaCutscene& cs : kVanillaCutscenes) {
        std::string name = cs.name;
        std::string nameLower = name;
        std::transform(nameLower.begin(), nameLower.end(), nameLower.begin(), ::tolower);
        if (lowered.empty() || nameLower.find(lowered) != std::string::npos) {
            result += name + "\n";
            count++;
        }
    }
    if (output != nullptr) {
        *output = result + std::to_string(count) + " cutscene(s)";
    }
    return 0;
}

void RegisterGanonsCurseVanillaCutsceneCommands() {
    auto console = Ship::Context::GetRawInstance()->GetConsole();
    console->AddCommand("gc_play_vanilla_cs",
                        { PlayVanillaCutsceneCommand,
                          "Ganon's Curse (dev): play a named vanilla cutscene by symbol." });
    console->AddCommand("gc_list_vanilla_cs",
                        { ListVanillaCutscenesCommand,
                          "Ganon's Curse (dev): list named vanilla cutscenes, optionally filtered." });
}

} // namespace

static RegisterShipInitFunc ganonsCurseVanillaCutsceneInitFunc(RegisterGanonsCurseVanillaCutsceneCommands);
