/**
 * Seven Sages - dev-only browser for vanilla cutscenes.
 *
 * `gc_play_vanilla_cs <symbol>` plays any vanilla cutscene that SoH exports as
 * a named OTR asset; `gc_list_vanilla_cs [filter]` lists them. This exists to
 * answer one question cheaply - "what does that shot actually look like?" -
 * while scoping 4c/4d, which are built on reusing vanilla camera work.
 *
 * The 73 entries below are every cutscene with a name. They are generated by
 * scanning soh/assets/scenes for the ALIGN_ASSET declarations, so the table is
 * exactly what the game ships, not a hand-maintained guess. Cutscenes without a
 * name - notably everything in the Chamber of Sages (kenjyanoma) and the ending
 * scene (hiral_demo) - are NOT reachable this way; they are scene cutscene
 * layers, selected by entering the scene with cutsceneIndex >= 0xFFF0. See
 * docs/opening-cutscene.md in the seven-sages repo.
 *
 * IMPORTANT CAVEAT: a cutscene's actor cues address actors by index in the
 * CURRENT scene. Playing a cutscene outside its home scene therefore gives you
 * its camera work and text, but any character it was meant to show will be
 * missing or wrong. To evaluate a character shot (e.g. the six *TrialSageCs
 * entries, all of which live in Ganon's Castle) you have to be standing in the
 * scene that owns it. Camera-only shots travel fine - that is exactly what the
 * 4b pipeline relies on.
 *
 * Dev tool: no gating beyond the debug console itself, and nothing here is
 * reachable in normal play.
 */
// Order matters - see the note in SevenSagesCutscenes.cpp. Plain-C++ includes
// first, before the extern "C" block pulls in the functions.h chain.
#include <soh/OTRGlobals.h>
#include "soh/ShipInit.hpp"

#include <ship/Context.h>
#include <ship/debug/Console.h>

#include <algorithm>
#include <string>
#include <vector>

// Pulls in the functions.h/variables.h/macros.h chain in the order that defines
// PlayState, Vec3f/Vec3s and gSaveContext before anything below needs them.
#include "SevenSagesCutscenes.h"

extern "C" {
extern PlayState* gPlayState;
}

#include <scenes/dungeons/bdan/bdan_scene.h>
#include <scenes/dungeons/ddan/ddan_scene.h>
#include <scenes/dungeons/ganon_tou/ganon_tou_scene.h>
#include <scenes/dungeons/ganontika/ganontika_scene.h>
#include <scenes/dungeons/ice_doukutu/ice_doukutu_scene.h>
#include <scenes/dungeons/jyasinboss/jyasinboss_scene.h>
#include <scenes/dungeons/ydan/ydan_scene.h>
#include <scenes/indoors/daiyousei_izumi/daiyousei_izumi_scene.h>
#include <scenes/indoors/hakasitarelay/hakasitarelay_scene.h>
#include <scenes/indoors/nakaniwa/nakaniwa_scene.h>
#include <scenes/indoors/tokinoma/tokinoma_scene.h>
#include <scenes/indoors/yousei_izumi_yoko/yousei_izumi_yoko_scene.h>
#include <scenes/misc/hakaana_ouke/hakaana_ouke_scene.h>
#include <scenes/overworld/spot00/spot00_scene.h>
#include <scenes/overworld/spot01/spot01_scene.h>
#include <scenes/overworld/spot02/spot02_scene.h>
#include <scenes/overworld/spot04/spot04_scene.h>
#include <scenes/overworld/spot05/spot05_scene.h>
#include <scenes/overworld/spot06/spot06_scene.h>
#include <scenes/overworld/spot07/spot07_scene.h>
#include <scenes/overworld/spot08/spot08_scene.h>
#include <scenes/overworld/spot09/spot09_scene.h>
#include <scenes/overworld/spot11/spot11_scene.h>
#include <scenes/overworld/spot12/spot12_scene.h>
#include <scenes/overworld/spot15/spot15_scene.h>
#include <scenes/overworld/spot16/spot16_scene.h>
#include <scenes/overworld/spot17/spot17_scene.h>
#include <scenes/overworld/spot18/spot18_scene.h>
#include <scenes/overworld/spot20/spot20_scene.h>

namespace {

struct VanillaCutscene {
    const char* name;
    const char* segment;
};

// Generated by scanning soh/assets/scenes for ALIGN_ASSET cutscene symbols.
const VanillaCutscene kVanillaCutscenes[] = {
    { "gDMTIntroCs", gDMTIntroCs },
    { "gDMTOwlCs", gDMTOwlCs },
    { "gDcOpeningCs", gDcOpeningCs },
    { "gDeathMountainCraterBoleroCs", gDeathMountainCraterBoleroCs },
    { "gDeathMountainCraterIntroCs", gDeathMountainCraterIntroCs },
    { "gDekuTreeIntroCs", gDekuTreeIntroCs },
    { "gDesertColossusIntroCs", gDesertColossusIntroCs },
    { "gFireBarrierCs", gFireBarrierCs },
    { "gFireTrialSageCs", gFireTrialSageCs },
    { "gForestBarrierCs", gForestBarrierCs },
    { "gForestTrialSageCs", gForestTrialSageCs },
    { "gGanonsCastleIntroCs", gGanonsCastleIntroCs },
    { "gGerudoFortressFirstCaptureCs", gGerudoFortressFirstCaptureCs },
    { "gGerudoFortressIntroCs", gGerudoFortressIntroCs },
    { "gGerudoValleyBridgeJumpFieldFortressCs", gGerudoValleyBridgeJumpFieldFortressCs },
    { "gGerudoValleyBridgeJumpFortressToFieldCs", gGerudoValleyBridgeJumpFortressToFieldCs },
    { "gGerudoValleyIntroCs", gGerudoValleyIntroCs },
    { "gGoronCityDarunia01Cs", gGoronCityDarunia01Cs },
    { "gGoronCityDaruniaCorrectCs", gGoronCityDaruniaCorrectCs },
    { "gGoronCityDaruniaWrongCs", gGoronCityDaruniaWrongCs },
    { "gGoronCityIntroCs", gGoronCityIntroCs },
    { "gGraveyardIntroCs", gGraveyardIntroCs },
    { "gGreatFairyDinsFireCs", gGreatFairyDinsFireCs },
    { "gGreatFairyDoubleDefenseCs", gGreatFairyDoubleDefenseCs },
    { "gGreatFairyDoubleMagicCs", gGreatFairyDoubleMagicCs },
    { "gGreatFairyFaroresWindCs", gGreatFairyFaroresWindCs },
    { "gGreatFairyMagicCs", gGreatFairyMagicCs },
    { "gGreatFairyNayrusLoveCs", gGreatFairyNayrusLoveCs },
    { "gHyruleCastleIntroCs", gHyruleCastleIntroCs },
    { "gHyruleFieldEastEponaJumpCs", gHyruleFieldEastEponaJumpCs },
    { "gHyruleFieldGateEponaJumpCs", gHyruleFieldGateEponaJumpCs },
    { "gHyruleFieldGetOoTCs", gHyruleFieldGetOoTCs },
    { "gHyruleFieldIntroCs", gHyruleFieldIntroCs },
    { "gHyruleFieldSouthEponaJumpCs", gHyruleFieldSouthEponaJumpCs },
    { "gHyruleFieldWestEponaJumpCs", gHyruleFieldWestEponaJumpCs },
    { "gHyruleFieldZeldaSongOfTimeCs", gHyruleFieldZeldaSongOfTimeCs },
    { "gIceCavernSerenadeCs", gIceCavernSerenadeCs },
    { "gJabuJabuIntroCs", gJabuJabuIntroCs },
    { "gKakarikoVillageIntroCs", gKakarikoVillageIntroCs },
    { "gKokiriForestDekuSproutCs", gKokiriForestDekuSproutCs },
    { "gLakeHyliaFireArrowsCS", gLakeHyliaFireArrowsCS },
    { "gLakeHyliaIntroCs", gLakeHyliaIntroCs },
    { "gLakeHyliaOwlCs", gLakeHyliaOwlCs },
    { "gLightBarrierCs", gLightBarrierCs },
    { "gLightTrialSageCs", gLightTrialSageCs },
    { "gLonLonRanchIntroCs", gLonLonRanchIntroCs },
    { "gMinuetCs", gMinuetCs },
    { "gRainbowBridgeCs", gRainbowBridgeCs },
    { "gShadowBarrierCs", gShadowBarrierCs },
    { "gShadowTrialSageCs", gShadowTrialSageCs },
    { "gSongOfStormsCs", gSongOfStormsCs },
    { "gSpiritBarrierCs", gSpiritBarrierCs },
    { "gSpiritBossNabooruKnuckleDefeatCs", gSpiritBossNabooruKnuckleDefeatCs },
    { "gSpiritBossNabooruKnuckleIntroCs", gSpiritBossNabooruKnuckleIntroCs },
    { "gSpiritTrialSageCs", gSpiritTrialSageCs },
    { "gSpot04Cs_10E20", gSpot04Cs_10E20 },
    { "gSunSongGraveSunSongTeachCs", gSunSongGraveSunSongTeachCs },
    { "gSunSongGraveSunSongTeachPart2Cs", gSunSongGraveSunSongTeachPart2Cs },
    { "gTempleOfTimeFirstAdultCs", gTempleOfTimeFirstAdultCs },
    { "gTempleOfTimeIntroCs", gTempleOfTimeIntroCs },
    { "gTempleOfTimePreludeCs", gTempleOfTimePreludeCs },
    { "gTowerBarrierCs", gTowerBarrierCs },
    { "gWaterBarrierCs", gWaterBarrierCs },
    { "gWaterTrialSageCs", gWaterTrialSageCs },
    { "gZeldasCourtyardGanonCs", gZeldasCourtyardGanonCs },
    { "gZeldasCourtyardLullabyCs", gZeldasCourtyardLullabyCs },
    { "gZeldasCourtyardMeetCs", gZeldasCourtyardMeetCs },
    { "gZeldasCourtyardWindowCs", gZeldasCourtyardWindowCs },
    { "gZorasDomainIntroCs", gZorasDomainIntroCs },
    { "gZorasFountainIntroCs", gZorasFountainIntroCs },
    { "spot02_scene_Cs_003C80", spot02_scene_Cs_003C80 },
    { "spot02_scene_Cs_005020", spot02_scene_Cs_005020 },
    { "spot05_scene_Cs_005730", spot05_scene_Cs_005730 },
};

int32_t PlayVanillaCutsceneCommand(std::shared_ptr<Ship::Console> console, std::vector<std::string> args,
                                   std::string* output) {
    if (gPlayState == nullptr) {
        if (output != nullptr) {
            *output = "no active play session";
        }
        return 1;
    }
    if (args.size() < 2) {
        if (output != nullptr) {
            *output = "usage: gc_play_vanilla_cs <symbol>  (see gc_list_vanilla_cs)";
        }
        return 1;
    }
    for (const VanillaCutscene& cs : kVanillaCutscenes) {
        if (args[1] == cs.name) {
            Cutscene_SetSegment(gPlayState, const_cast<char*>(cs.segment));
            gSaveContext.cutsceneTrigger = 1;
            if (output != nullptr) {
                *output = "playing " + args[1] +
                          " (actor shots only render correctly in the scene that owns them)";
            }
            return 0;
        }
    }
    if (output != nullptr) {
        *output = "unknown cutscene: " + args[1] + " - try gc_list_vanilla_cs";
    }
    return 1;
}

int32_t ListVanillaCutscenesCommand(std::shared_ptr<Ship::Console> console, std::vector<std::string> args,
                                    std::string* output) {
    std::string filter = args.size() >= 2 ? args[1] : "";
    std::string lowered = filter;
    std::transform(lowered.begin(), lowered.end(), lowered.begin(), ::tolower);

    std::string result;
    int32_t count = 0;
    for (const VanillaCutscene& cs : kVanillaCutscenes) {
        std::string name = cs.name;
        std::string nameLower = name;
        std::transform(nameLower.begin(), nameLower.end(), nameLower.begin(), ::tolower);
        if (lowered.empty() || nameLower.find(lowered) != std::string::npos) {
            result += name + "\n";
            count++;
        }
    }
    if (output != nullptr) {
        *output = result + std::to_string(count) + " cutscene(s)";
    }
    return 0;
}

/**
 * `gc_chamber <0-4>` - enter the Chamber of Sages set up to play one sage's
 * awakening cutscene.
 *
 * Warping to the chamber by raw entrance index is not enough. Each sage's
 * cutscene lives inside that sage's own actor overlay and only fires when
 * gSaveContext.chamberCutsceneNum selects it AND sceneLayer < 4 - see
 * z_demo_sa.c:255 and its four siblings. Vanilla sets both from Door_Warp1
 * (the boss blue warp); this reproduces that setup so the cutscenes can be
 * evaluated without playing a dungeon to get there.
 *
 *   0 Saria (Forest)   1 Darunia (Fire)   2 Ruto (Water)
 *   3 Nabooru (Spirit) 4 Impa (Shadow)
 *
 * Rauru has no entry: he is not one of the chamberCutsceneNum cases.
 */
int32_t ChamberOfSagesCommand(std::shared_ptr<Ship::Console> console, std::vector<std::string> args,
                              std::string* output) {
    if (gPlayState == nullptr) {
        if (output != nullptr) {
            *output = "no active play session";
        }
        return 1;
    }
    if (args.size() < 2) {
        if (output != nullptr) {
            *output = "usage: gc_chamber <0-4>  (0 Saria, 1 Darunia, 2 Ruto, 3 Nabooru, 4 Impa)";
        }
        return 1;
    }

    int32_t which = -1;
    try {
        which = std::stoi(args[1]);
    } catch (...) {
        which = -1;
    }
    if (which < 0 || which > 4) {
        if (output != nullptr) {
            *output = "expected 0-4 (0 Saria, 1 Darunia, 2 Ruto, 3 Nabooru, 4 Impa)";
        }
        return 1;
    }

    // Range-checked to 0-4 just above, so the u8 field takes it whole.
    gSaveContext.chamberCutsceneNum = static_cast<u8>(which);

    // sceneLayer is derived from cutsceneIndex on load; anything >= 0xFFF0 puts
    // it at 4+ and the sage checks would fail. Write nextCutsceneIndex, not
    // cutsceneIndex: z_play.c:424 copies next -> current on load whenever next
    // isn't 0xFFEF, so writing current alone only survives while next happens to
    // be at its resting value. Vanilla's blue warp writes next; match it.
    gSaveContext.nextCutsceneIndex = 0;
    gSaveContext.cutsceneIndex = 0;

    // CAVEAT, unresolved as of 2026-07-30: this does NOT control which sage actor
    // spawns. kenjyanoma has three alternate room headers besides the base, and
    // alternate headers are picked by sceneLayer - which, once cutsceneIndex is 0,
    // is decided by Link's age and the time of day, not by anything here. On the
    // one save this was tried, only Darunia ever appeared while the return warp
    // was correct for all five, which is the signature of "chamberCutsceneNum is
    // read, actor presence is decided elsewhere". Before theorising further, open
    // the Actor Viewer in the chamber and look at whether the sage is in the room
    // at all - see seven-sages/docs/opening-cutscene.md section 3c.

    gPlayState->nextEntranceIndex = 0x6B; // ENTR_CHAMBER_OF_THE_SAGES_0
    gPlayState->transitionTrigger = TRANS_TRIGGER_START;
    gPlayState->transitionType = TRANS_TYPE_FADE_WHITE_SLOW;
    gSaveContext.nextTransitionType = TRANS_TYPE_FADE_WHITE_SLOW;

    if (output != nullptr) {
        static const char* kNames[] = { "Saria", "Darunia", "Ruto", "Nabooru", "Impa" };
        *output = std::string("entering Chamber of Sages set up for ") + kNames[which];
    }
    return 0;
}

void RegisterSevenSagesVanillaCutsceneCommands() {
    auto console = Ship::Context::GetRawInstance()->GetConsole();
    console->AddCommand("gc_play_vanilla_cs",
                        { PlayVanillaCutsceneCommand,
                          "Seven Sages (dev): play a named vanilla cutscene by symbol." });
    console->AddCommand("gc_list_vanilla_cs",
                        { ListVanillaCutscenesCommand,
                          "Seven Sages (dev): list named vanilla cutscenes, optionally filtered." });
    console->AddCommand("gc_chamber",
                        { ChamberOfSagesCommand,
                          "Seven Sages (dev): enter the Chamber of Sages set up for one sage's cutscene (0-4)." });
}

} // namespace

static RegisterShipInitFunc sevenSagesVanillaCutsceneInitFunc(RegisterSevenSagesVanillaCutsceneCommands);
